---
- name: Restart Chrony on CentOS
  service:
    name: chronyd
    state: restarted
    enabled: yes
  when: ansible_distribution == "CentOS"

- name: Restart NTP on Ubuntu
  service:
    name: ntp
    state: restarted
    enabled: yes
  when: ansible_distribution == "Ubuntu"
