---
- name: Fetching chrony.conf file from web01
  hosts: all
  become: yes
  tasks:
    - name: Copy Chrony.conf file from CentOS to templates
      fetch:
        src: /etc/chrony.conf
        dest: /home/ubuntu/ansible_project/file
      register: fetch_result
      when: ansible_distribution == "CentOS"

    - name: Copy ntp.conf file from Ubuntu to templates
      fetch:
        src: /etc/ntpsec/ntp.conf
        dest: /home/ubuntu/ansible_project/templates/file
      register: fetch_result
      when: ansible_distribution == "Ubuntu"

    - name: Deploy ntp agent conf on centos
      template:
        src: templates/ntpconf_centos
        dest: /etc/chrony.conf
        backup: yes
      when: ansible_distribution == "CentOS"

    - name: Deploy ntp agent conf on Ubuntu
      template:
        src: templates/ntpconf_ubuntu
        dest: /etc/ntp.conf
        backup: yes
      when: ansible_distribution == "Ubuntu"

    - name: Restart Chrony on CentOS
      service:
        name: chronyd
        state: restarted
        enabled: yes
      when: ansible_distribution == "CentOS"

    - name: Restart NTP on ubuntu
      service:
        name: ntp
        state: restarted
        enabled: yes
      when: ansible_distribution == "Ubuntu"
